#cloud-config
package_update: true
package_upgrade: true
packages:
  - wireguard
  - wireguard-tools
  - curl
write_files:
  - path: /etc/wireguard/wg0.conf
    permissions: '0600'
    content: |
      [Interface]
      PrivateKey = ${wg_private_key}
      Address = 10.0.0.2/24
      DNS = 8.8.8.8, 8.8.4.4

      [Peer]
      PublicKey = ${server_public_key}
      Endpoint = ${server_endpoint}
      AllowedIPs = 10.0.0.0/24, 10.0.1.0/24
      PersistentKeepalive = 25
runcmd:
  - sysctl -w net.ipv4.ip_forward=1
  - systemctl enable wg-quick@wg0
  - systemctl start wg-quick@wg0 